### ISSUE TITLE
PAsar a Roberto el parametro que se debe de configurar en los archivos terraform para la aplicación de versionado en los buckets

### ISSUE THREAD

**Issue by milagrosmarotte1** [milagrosmarotte1/primer-proyecto#7]

**Comment by martinferrini-cloud** [comment]
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_versioning

resource "aws_s3_bucket" "example" {
  bucket = "example-bucket"
}

resource "aws_s3_bucket_acl" "example" {
  bucket = aws_s3_bucket.example.id
  acl    = "private"
}

resource "aws_s3_bucket_versioning" "versioning_example" {
  bucket = aws_s3_bucket.example.id
  versioning_configuration {
    status = "Enabled"
  }
}

Sabemos la versión del módulo de AWS que está utilizando PAE?

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket

Esto es para la versión - 5.73.0

**Comment by milagrosmarotte1** [comment]
Se le paso a Roberto estos parametros y el los paso al equipo de desarrollo. (Referencia mail "RV: Aplicación de políticas de versionado de S3")
